Add validation of extents
metadata101/iso19139.ca.HNAP pull request #346
Opened 2023-07-27 13:12 UTC by ianwallen

Add validation of extents
Also extents should be mandatory when gmd:spatialRepresentationType exists.

In the past some of validation was removed for the extents however I think it was incorrect.  It was remove to support non spatial data however instead of removing it completely, it should have probably just been checked when gmd:spatialRepresentationType exists.

This fixes an issue where records would validate however when publishing to FGP, the record would fail due to extent validation issues. Since FGP required spatialRepresentationType, making the check only enforce the rules when spatialRepresentationType  exists seems to fix the issue with FGP and also still works for non-spatial metadata which does not have spatialRepresentationType.

2023-08-09 16:02 UTC, jodygarnett reviewed
This change makes sense to me, but I will need to manually test before approving.

aside: In looking at https://github.com/geonetwork/core-geonetwork/blob/main/web/src/test/java/org/fao/geonet/kernel/schema/SchematronRulesIsoTest.java#L65-L69 it appears we can add integration tests.

2023-08-09 20:22 UTC, jodygarnett commented
I am having trouble running this:

> Error happened while calling service
> Failed to compile stylesheet. 1 error detected.

```
Error on line 397 column 61 of inflate-metadata.xsl:
  SXXP0003: Error reported by XML parser: The prefix "gml" for element "gml:TimePeriod" is not bound.
2023-08-09 13:21:59,840 ERROR [geonetwork] - Failed to compile stylesheet. 1 error detected.
javax.xml.transform.TransformerConfigurationException: Failed to compile stylesheet. 1 error detected.
	at net.sf.saxon.PreparedStylesheet.prepare(PreparedStylesheet.java:176)
	at net.sf.saxon.TransformerFactoryImpl.newTemplates(TransformerFactoryImpl.java:139)
```

2023-08-09 20:55 UTC, jodygarnett requested changes
Looks like we need to make sure TimePeriod is defined

2023-08-09 20:55 UTC, jodygarnett commented on src/main/plugin/iso19139.ca.HNAP/inflate-metadata.xsl
> +                  <gml:TimePeriod gml:id="{generate-id(.)}">
I am encountering a problem here:
> Error on line 397 column 61 of inflate-metadata.xsl:
>  SXXP0003: Error reported by XML parser: The prefix "gml" for element "gml:TimePeriod" is not bound.

2023-08-09 21:06 UTC, jodygarnett commented
I can find this commit https://github.com/metadata101/iso19139.ca.HNAP/commit/536c78cc650f810cfe7638400934dabace102bc4#diff-f70a3de7483485eb7a8adc9a5aba59c8378954b840ac025a162669ab962e6fd8 which removed a check for ``gmd:spatialRepresentationType``.

I cannot see any reference to ``gml`` in the file history.

Adding `gml` does not help (as I have to find where this is mapped to a xsd file):
```
xmlns:gml="http://www.opengis.net/gml/3.2"
```

2023-08-09 21:19 UTC, jodygarnett commented
@ianwallen I have pushed up a small fix and this PR is working for me locally now

2023-08-10 05:38 UTC, jodygarnett reviewed
I have addressed the issue I encountered and the editor now functions.

2023-08-10 10:30 UTC, ianwallen commented
> I have addressed the issue I encountered and the editor now functions.

@jodygarnett  It is odd that I did not get that error on my locale testing.  In either case, your change looks good - Thank you.

2023-08-10 22:15 UTC, jodygarnett approved these changes
Resorted to manual testing, the infrastructure for running schematron tests occurs very late in the build process and is not available during schema plugin compilation.

2023-08-11 09:45 UTC, merged