improve org name selector (and bug fix)
metadata101/iso19139.ca.HNAP pull request #35
Opened 2020-04-17 16:17 UTC by davidblasby

Changes to Org name selector;

a) changed the first part ("Government of Canada") to be a keyword picker that defaults to "Government of Canada".  The included thesaurus can be added to.  Users can just type in whatever they want as well.

b) fixed an issue with saving.  Problem was when removing the default language value.  The change wouldn't actually take place.

2020-04-21 21:01 UTC, ianwallen requested changes
I send an email regarding a full review - for which I wanted ECCC to also see my comments.

2020-04-21 21:01 UTC, ianwallen commented on src/main/plugin/iso19139.ca.HNAP/layout/layout-custom-fields.xsl
> +                "eng": "Main Organization Enitity",
typo "Entity"?
But I also recommend not having this title.
But if it is kept then translation is required in next line

2020-04-24 11:52 UTC, ianwallen commented
Based on email discussions, it sounds like the following should be done.

- Remove: "Main Organization Enitity" header and just let the first box go beside the main field tiltle of "Organization Name"

- The second title(currently Government of Canada Organization) should be changed to the following:
EN - “Department/Agency”
FR - “Département/agence”

2020-04-30 04:26 UTC, davidblasby commented
Ok, text change.
Also, fixed some layout issues (add commit to GN-core)

2020-04-30 10:47 UTC, ianwallen commented
Could you please reference the pull request from GN-core that fixed some layout issues.

2020-04-30 15:15 UTC, davidblasby commented
https://github.com/geonetwork/core-geonetwork/pull/4652
(its already been merged to master)

2020-04-30 16:03 UTC, ianwallen commented
That pull request is not flagged for 3.10.x.   I don't believe we should have dependencies on master? Maybe you can make a request on that pull request to have it flagged for 3.10.x?

2020-04-30 16:28 UTC, davidblasby commented
I was going to make a backport PR.
I don't think I have permission on the PRs to attach to milestones...

2020-04-30 16:32 UTC, davidblasby commented
https://github.com/geonetwork/core-geonetwork/pull/4659

2020-04-30 16:49 UTC, davidblasby commented
@ianwallen - backport is merged.  This should be ok to merge now?
I can still work on it if there are any issue/changes.  
I want to consolidate where we are and get everything merged.

2020-05-01 17:31 UTC, ianwallen commented
@davidblasby  It looks good.  I only have 2 issues.

- At one point you mentioned that you had disabled the "all" in the language and I think it should be enabled again to be consistent with the rest of the interface.  

- Also, I'm not able to get these changes to work when I test it using the geonetwork core 3.10.x branch.  I can only get it to work when using the master branch.  So it looks like the 3.10.x branch is missing some cherry picks.   Could you look into this and identify the missing commits and maybe ask someone to cherry pick those commits. 

Thank you

2020-05-01 17:34 UTC, davidblasby commented
@ianwallen  - I am trying to get all the commits into 3.10.x.  Its a process...

I am skeptical with adding an "all".  The other "all" buttons are just for a single fields - it's unclear how this should look as its actually 3 fields somewhat combined.

What should the first 2 fields look like when "all" is pressed?

2020-05-01 17:35 UTC, davidblasby commented
I currently have 6 open HNAP PRs - I think we need to consolidate before doing any new work.

2020-05-01 18:30 UTC, ianwallen commented
Is this organization a sort of block/group input?  Is why it is more complex? I would think that each of the 3 fields would have the language selection (all/one/eng/fra) as I believe each once can be changed independent of the other.  Or they could all change as a group - as they will have the eng/fra in the top right of the text box it would be easy to identify the language of each box.

As this may be a little more complex - we can look at this one as a separate PR in the future.

So if you can track down the missing cherry pick commits and make it so this PR works on the 3.10.x branch then I will approve this PR.

2020-05-01 18:42 UTC, davidblasby commented
I'm going to go through all the PR/commits I've made and see which ones aren't in 3.10.x

2020-05-01 18:43 UTC, davidblasby commented
We can go through the org UX again and I can fix it up so everyone is happy.

2020-05-01 19:28 UTC, merged